version: '3.8'
services:
  angular:
    build: .
    ports:
      - "4200:4200"
    restart: on-failure
    container_name: ng-signal
    volumes:
      - ./app:/app
#      - ./node_modules:/app/node_modules
